# Generated by Django 5.1.2 on 2024-10-15 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('api_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('state', models.CharField(choices=[('Running', 'Running'), ('Busy', 'Busy'), ('Stopped', 'Stopped'), ('Unknown', 'Unknown')], max_length=255)),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('img_url', models.CharField(blank=True, max_length=255)),
                ('website_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nativeName', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('state', models.CharField(choices=[('Running', 'Running'), ('Busy', 'Busy'), ('Stopped', 'Stopped'), ('Unknown', 'Unknown')], max_length=255)),
                ('priority', models.IntegerField()),
                ('is_message_system', models.BooleanField()),
                ('is_arabic', models.BooleanField()),
                ('is_auth', models.BooleanField()),
                ('is_cookies', models.BooleanField()),
                ('is_stream', models.BooleanField()),
                ('is_parameter', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('state', models.CharField(choices=[('Running', 'Running'), ('Busy', 'Busy'), ('Stopped', 'Stopped'), ('Unknown', 'Unknown')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ManyToManyField(to='chat.apikey')),
            ],
        ),
        migrations.CreateModel(
            name='ApiOwner',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type_service', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('research', 'Research')], default='text', max_length=10)),
                ('type_price', models.CharField(choices=[('free', 'Free'), ('paide', 'Paide')], max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('state', models.CharField(choices=[('Running', 'Running'), ('Busy', 'Busy'), ('Stopped', 'Stopped'), ('Unknown', 'Unknown')], max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_options_id', models.ManyToManyField(blank=True, to='chat.apioption')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAI',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('type_service', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('research', 'Research')], default='text', max_length=10)),
                ('is_active', models.BooleanField()),
                ('is_stream', models.BooleanField()),
                ('is_web_search', models.BooleanField(default=False)),
                ('is_allow_image', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('Running', 'Running'), ('Busy', 'Busy'), ('Stopped', 'Stopped'), ('Unknown', 'Unknown')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.apiowner')),
                ('company_ai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.companyai')),
                ('languages', models.ManyToManyField(blank=True, to='chat.language')),
                ('provider', models.ManyToManyField(blank=True, to='chat.provider')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_like', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.modelai')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('is_like', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.modelai')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.character')),
                ('lang_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.language')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('research', 'Research')], default='text', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('is_pin', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_like', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.language')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.modelai')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='TextTranMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.language')),
            ],
        ),
        migrations.CreateModel(
            name='MessageUserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
                ('image_ai', models.ManyToManyField(to='chat.imageai')),
                ('text_tran', models.ManyToManyField(blank=True, to='chat.texttranmessage')),
            ],
        ),
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
                ('message_ai', models.ManyToManyField(to='chat.messageai')),
                ('text_tran', models.ManyToManyField(blank=True, to='chat.texttranmessage')),
            ],
        ),
        migrations.AddField(
            model_name='messageai',
            name='text_tran',
            field=models.ManyToManyField(blank=True, to='chat.texttranmessage'),
        ),
    ]
